const CUSTOMER_HEADER_NAME = "X-Customer-ID";
const ROLE_SAAS_ACCOUNT_ADMIN = "SAAS_ACCOUNT_ADMIN";
const ROLE_SAAS_ACCOUNT_OWNER = "SAAS_ACCOUNT_OWNER";
const ROLE_SAAS_ACCOUNT_MEMBER = "SAAS_ACCOUNT_MEMBER";

export {
  CUSTOMER_HEADER_NAME,
  ROLE_SAAS_ACCOUNT_ADMIN,
  ROLE_SAAS_ACCOUNT_OWNER,
  ROLE_SAAS_ACCOUNT_MEMBER,
};
