const ACCOUNT_HEADER_NAME = "x-account-id";
const ACCOUNT_INVITATION_ACCEPT_LINK_PATH =
  "/signup/token/:token?accountId=:accountId";
const NANOID_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";
const NANOID_SIZE = 8;
const ROLE_SAAS_ACCOUNT_ADMIN = "SAAS_ACCOUNT_ADMIN";
const ROLE_SAAS_ACCOUNT_OWNER = "SAAS_ACCOUNT_OWNER";
const ROLE_SAAS_ACCOUNT_MEMBER = "SAAS_ACCOUNT_MEMBER";

export {
  ACCOUNT_HEADER_NAME,
  ACCOUNT_INVITATION_ACCEPT_LINK_PATH,
  NANOID_ALPHABET,
  NANOID_SIZE,
  ROLE_SAAS_ACCOUNT_ADMIN,
  ROLE_SAAS_ACCOUNT_OWNER,
  ROLE_SAAS_ACCOUNT_MEMBER,
};
