import { QuerySqlToken, sql } from "slonik";
import { ZodTypeAny } from "zod";

import type { SaasConfig } from "../types";

const createCustomersTableQuery = (
  config: SaasConfig,
): QuerySqlToken<ZodTypeAny> => {
  const customers = config.tables?.customers?.name as string;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([customers])} (
      id VARCHAR(36) DEFAULT gen_random_uuid() PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      organization_name VARCHAR(255),
      registered_number VARCHAR(255),
      tax_id VARCHAR(255),
      individual BOOLEAN NOT NULL DEFAULT FALSE,
      slug VARCHAR(24),
      database VARCHAR(10),
      domain VARCHAR(255),
      UNIQUE (slug),
      UNIQUE (database),
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
  `;
};

const createCustomerAddressesTableQuery = (
  config: SaasConfig,
): QuerySqlToken<ZodTypeAny> => {
  const customer_addresses = config.tables?.customerAddresses?.name as string;
  const customers = config.tables?.customers?.name as string;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([customer_addresses])} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id VARCHAR(36) NOT NULL,
      type_id SMALLINT NOT NULL,
      street VARCHAR(30) NOT NULL,
      street2 VARCHAR(30),
      city VARCHAR(30) NOT NULL,
      zip_code VARCHAR(30),
      state VARCHAR(30),
      country VARCHAR(2) NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
      CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES ${sql.identifier([customers])} (id)
        ON DELETE CASCADE
    );
  `;
};

const createCustomerUsersTableQuery = (
  config: SaasConfig,
): QuerySqlToken<ZodTypeAny> => {
  const customer_users = config.tables?.customerUsers?.name as string;
  const customers = config.tables?.customers?.name as string;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([customer_users])} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id VARCHAR(36) NOT NULL,
      user_id VARCHAR(255) NOT NULL,
      role_id VARCHAR(255) NOT NULL,
      date_start TIMESTAMP,
      date_end TIMESTAMP,
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
      UNIQUE (customer_id, user_id),
      CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES ${sql.identifier([customers])} (id)
        ON DELETE CASCADE
    );
  `;
};

export {
  createCustomerAddressesTableQuery,
  createCustomersTableQuery,
  createCustomerUsersTableQuery,
};
